### PR TITLE
ZENKO-2609 Move Golang Vault client into its own repo

### PR DESCRIPTION
**Pull request by nicolas2bert**
Move Go Vault client (currently in `scality/vaultclient`) into its own repository.

Note: Code has already been reviewed.

Motivation: 
- Module’s import path depends on the GitHub project code path
- For updates, vendor, download, checksum… Go module should be independent of other (javascript) packages changes/updates done in the same repository.

TODO post-merge: 
- add documentation to README.md
- remove module from `scality/vaultclient`

### CODE REVIEW

**Review by jonathan-gramain — COMMENTED** [review]
While the move looks good, two process-related questions:
- no ticket number in the branch name, is it wanted?
- if it is a NG feature, shouldn't the target branch be development/2.0?

**Comment by nicolas2bert** [comment]
I don't think having the ticket number in the branch name is required as long as we mention it in the commit title.
I have been using development/1.0 for ZenkoUI as well. I don't think the number matters here.
Let me double-check both concerns with @rahulreddy. 
Thanks for your review. :)

**Comment by anurag4DSB** [comment]
A proper branch name might be required. if you enable Bert-e on this.

**Comment by rachedbenmustapha** [comment]
Zenko is going to be 2.0, but individual components can have their own lifespan - lockstep versions across the board was a limitation of the federation build thing.

**Comment by nicolas2bert** [comment]
I will open a PR with a proper branch name. Even though Bert-e is not set, I think it's good to follow common practices.

https://github.com/scality/vaultclient-go/pull/2

**Review by anurag4DSB — APPROVED** [review]
After this merge, I strongly suggest adding usability instructions in README.md. I know you are occupied with other things.

Also, as this is a move, will the code be deleted from Vaultclient?

**Comment by nicolas2bert** [comment]
@anurag4DSB these two concerns have already been mentioned inside this PR description "post-merge" section.

**Pull request closed without merging**
